amaysim/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#homepage'

 get 'help/mobile', to: 'pages#help'
 #get 'pages/help', :to => 'pages#help'

 get 'plans/mobile-plans', to: 'plans#mobile'

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

amaysim/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

amaysim/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

amaysim/app/controllers/concerns/plans_controller.rb
class PlansController < ApplicationController
  def mobile
  end
end

amaysim/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def help
    @names = ["first", "second"]
  end
end

amaysim/app/helpers/application_helper.rb
module ApplicationHelper
end

amaysim/app/helpers/pages_helper.rb
module PagesHelper
end

amaysim/app/views/layouts/_box.html.erb
<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout/public/cta/2016-10/queen_orange_77.jpg?itok=hJ--cPzy" alt="">
    <div class="card-body">
      <h4 class="card-title">sim-only mobile plans</h4>
      <p class="card-text">Unlimited standard talk & text with heaps of data for use in Oz</p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><a href=https://www.amaysim.com.au/plans/mobile-plansmobile>mobile plans</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/big_teaser/public/2017-07/phone_hand_purple.png?itok=XSL37udr" alt="">
    <div class="card-body">
      <h4 class="card-title">nbn broadband plans</h4>
      <p class="card-text">Unlimited data with superfast speeds. No lock-in contracts.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">
        <a href=https://www.amaysim.com.au/plans/nbn>nbn plans</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://static1.squarespace.com/static/547548e4e4b0dce34cdd7ed8/t/58a82f1786e6c0c3738c8bcc/1487417154292/" alt="">
    <div class="card-body">
      <h4 class="card-title">data-only plans</h4>
      <p class="card-text">Mobile broadband for your tablets and devices, for use in Oz</p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><a href=https://www.amaysim.com.au/plans/data-plans>data-onlyplans</small>
    </div>
  </div>
</div>

amaysim/app/views/layouts/_jumbo.html.erb
<div class="jumbotron jumbotron-fluid jumbo">
  <div class="container">
    <h1 class="display-3">win a Google Home, Chromecast Ultra and a year of nbn™</h1>
    <p class="lead">Sign up to any nbn plan before 31 August to go into the draw. Plans start from $40 a month.</p>
    <a href=https://www.amaysim.com.au/terms-policies/competitions-promos>"T&C'S Apply"
  </div>
  <img src="https://www.amaysim.com.au/sites/default/files/styles/retina_2x/public/2017-08/Header_Image-nbn-com-2.png?itok=cnLdQHJt"
  alt="brand" width="1000" height="300">
  <div class="topright"></div>
</div>

amaysim/app/views/layouts/_nav.html.erb
<!-- _nav.html.erb -->

<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  <div class="container">
  <a class="navbar-brand text-white" href="#">amaysim</a>
  <button class="navbar-toggler" type="button"
  data-toggle="collapse" data-target="#navbarNavDropdown"
  aria-controls="navbarNavDropdown" aria-expanded="false"
  aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse"
  id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">plans <span
          class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">about</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">help</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
        href="http://example.com" id="navbarDropdownMenuLink"
        data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</div>
</div>
</nav>

amaysim/app/views/layouts/_white.html.erb
<div class="bg-white">
  <div class="container">
    <ul id="list">
      <li>Activate sim</li>
      <li>login</li>
    </ul>
  </div>
  </div>

amaysim/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/white' %>
    <title>Amaysim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <a href="/help/mobile">Help</a>
    <% link_to 'Help', help_mobile_path %>
    <% link_to 'Help URL', help_mobile_url%> -->

    <%= render 'layouts/nav' %>
    <%= render 'layouts/jumbo' %>
    <%= render 'layouts/box' %>

    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

amaysim/app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

<h1>
<% ["first", "second"].each do |name| %>
  <!-- <h3>something to repeat</h3> -->
  <%# bag = 4 + 5 %>
  <%= name %><br>
<% end %>
</h1>

amaysim/app/views/pages/homepage.html.erb
<h1>Pages#homepage</h1>
<p>Find me in app/views/pages/homepage.html.erb</p>

amaysim/app/views/plans/mobile.html.erb
<!-- mobile.html.erb -->
<h1>You've made it to /plans/mobile-plans</h1>